"""Chair of the Board — Phase 2 (Validator + Judge).

Two-stage evaluation:
  1. verify_grounding()  — DETERMINISTIC. Cross-checks every numeric claim an
     agent made against the real snapshot. Hallucinated/contradicted numbers are
     caught here, not left to the LLM's good faith. This is the anti-hallucination
     core of the project.
  2. judge()             — LLM-as-judge. Given the arguments + their grounding
     scores, weights them and issues the final verdict.
"""
from __future__ import annotations

import json
import re
from typing import Any

from . import config
from .llm import chat_json

VERDICTS = ["Strong Buy", "Accumulate", "Hold", "Reduce"]
DISCLAIMER = (
    "EDUCATIONAL ONLY — not investment advice. Generated by an AI debate system. "
    "Markets carry risk; consult a SEBI-registered advisor before investing."
)


# Matches the structured citations agents emit, e.g. "sma_20=1385.15",
# "macd.histogram=-2.8641", "bollinger_lower=1293.49" (comma-separated allowed).
_METRIC_PAIR_RE = re.compile(r"([A-Za-z_][\w.]*)\s*=\s*(-?\d[\d,]*\.?\d*)")


def _resolve_metric(name: str, snapshot: dict[str, Any]) -> float | None:
    """Resolve a cited metric name to its real snapshot value, or None if it doesn't exist.

    Handles three naming styles the model uses interchangeably:
      - top-level keys with underscores:  rsi_14, sma_20, week52_low, volume_vs_avg_pct
      - dotted nested paths:               macd.histogram, bollinger.lower
      - underscore-flattened nested:       macd_histogram, bollinger_lower
    """
    name = name.strip()

    def as_num(v: Any) -> float | None:
        if isinstance(v, bool) or not isinstance(v, (int, float)):
            return None
        return float(v)

    # 1. direct top-level key
    if name in snapshot:
        n = as_num(snapshot[name])
        if n is not None:
            return n
    # 2. dotted nested path
    if "." in name:
        cur: Any = snapshot
        for part in name.split("."):
            cur = cur.get(part) if isinstance(cur, dict) else None
        n = as_num(cur)
        if n is not None:
            return n
    # 3. underscore-flattened nested (try each split point)
    if "_" in name:
        parts = name.split("_")
        for i in range(1, len(parts)):
            outer, inner = "_".join(parts[:i]), "_".join(parts[i:])
            sub = snapshot.get(outer)
            if isinstance(sub, dict) and isinstance(sub.get(inner), (int, float)):
                return float(sub[inner])
    return None


def _value_matches(claimed: float, truth: float, tol: float = 0.01) -> bool:
    """True if a claimed number is within `tol` (relative) of the real value."""
    if truth == 0:
        return abs(claimed) < 1e-9
    return abs(claimed - truth) / abs(truth) <= tol


def verify_grounding(argument: dict[str, Any], snapshot: dict[str, Any]) -> dict[str, Any]:
    """Score how well an argument's CITED METRICS match the real snapshot.

    Only the structured `cited_metric` field is graded — each `name=value` pair is
    resolved against the snapshot and checked for value match. Derived figures in the
    prose (percentages, news amounts) are argumentation, not evidence, so they are not
    penalized. A point is verified iff every metric it cites resolves and matches.

    grounding = verified / (verified + unverified)  (1.0 if no metrics were cited).
    """
    verified: list[str] = []
    unverified: list[str] = []
    bad_metrics: list[str] = []

    for point in argument.get("points", []):
        claim = point.get("claim", "")
        pairs = _METRIC_PAIR_RE.findall(point.get("cited_metric", "") or "")
        if not pairs:
            continue  # qualitative claim — neither rewarded nor penalized

        point_ok = True
        for name, raw in pairs:
            truth = _resolve_metric(name, snapshot)
            if truth is None or not _value_matches(float(raw.replace(",", "")), truth):
                point_ok = False
                bad_metrics.append(f"{name}={raw}")
        (verified if point_ok else unverified).append(claim)

    total = len(verified) + len(unverified)
    grounding = 1.0 if total == 0 else round(len(verified) / total, 2)
    return {
        "grounding": grounding,
        "verified": verified,
        "unverified": unverified,  # claims citing fabricated / non-existent metrics
        "unverified_metrics": bad_metrics,
    }


def judge(
    arguments: dict[str, dict[str, Any]],
    snapshot: dict[str, Any],
    news: list[dict[str, str]],
) -> dict[str, Any]:
    """Grade arguments, weight by grounding x confidence, return the final verdict."""
    grading = {p: verify_grounding(a, snapshot) for p, a in arguments.items()}

    # Deterministic weights so the verdict never rests on hallucinated claims.
    weights: dict[str, float] = {}
    for p, a in arguments.items():
        weights[p] = round(grading[p]["grounding"] * float(a.get("confidence", 0.5)), 3)

    user = json.dumps(
        {
            "snapshot": snapshot,
            "arguments": arguments,
            "grounding_scores": grading,
            "computed_weights": weights,
            "allowed_verdicts": VERDICTS,
        },
        indent=2,
        default=str,
    )
    system = (
        "You are the CHAIR OF THE INVESTMENT BOARD. Three analysts (bull, bear, risk manager) "
        "have argued. You are given each argument, a DETERMINISTIC grounding score (fraction of "
        "their numeric claims that match real data), and a computed weight (grounding x confidence). "
        "Trust well-grounded arguments; discount poorly grounded ones REGARDLESS of how confident "
        "they sounded. Choose exactly one verdict from allowed_verdicts and explain why in 2-3 "
        'sentences. Return JSON: {"verdict": "...", "rationale": "...", '
        '"per_agent": {"bull": {"weight": n}, "bear": {"weight": n}, "neutral": {"weight": n}}}.'
    )

    result = chat_json(
        system,
        user,
        deployment=config.CHAT_DEPLOYMENT if config.llm_backend() == "azure" else None,
        temperature=0.2,
        context={"snapshot": snapshot},
    )

    if result.get("verdict") not in VERDICTS:
        result["verdict"] = _fallback_verdict(arguments, weights)

    # Attach the authoritative deterministic data (never trust LLM self-report here).
    result["grounding_scores"] = grading
    result["weights"] = weights
    result["disclaimer"] = DISCLAIMER
    return result


def _fallback_verdict(arguments: dict[str, dict], weights: dict[str, float]) -> str:
    """Map weighted stances to a verdict if the LLM returns an invalid one."""
    score = 0.0
    for p, w in weights.items():
        stance = str(arguments[p].get("stance", "")).lower()
        sign = 1 if ("buy" in stance) else -1 if ("sell" in stance or "short" in stance or "reduce" in stance) else 0
        score += sign * w
    if score > 0.4:
        return "Strong Buy"
    if score > 0.1:
        return "Accumulate"
    if score < -0.2:
        return "Reduce"
    return "Hold"
